name: "Build and Test"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        python-version: ['3.8', '3.10', '3.12']
      fail-fast: false
    steps:
      - name: "Software Install - Ubuntu"
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo apt-get install -y \
            build-essential \
            ca-certificates \
            coreutils \
            curl \
            git \
            gpg \
            gpgv \
            gzip \
            libboost-python-dev \
            libcfitsio-dev \
            libfftw3-dev \
            libgdbm-dev \
            libgsl-dev \
            pkg-config \
            software-properties-common
      - name: "Software Install - MacOS"
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install \
            gdbm \
            fftw \
            gsl \
            pkg-config
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
      - name: "Software Install - Python" 
        run: |
          python -m pip install \
            setuptools \
            numpy \
            matplotlib \
            scipy \
            ephem \
            pylint \
            coverage
      - name: "Build and Install"
        run: python -m pip install .
      - name: Test
        env:
          PYDEVD_DISABLE_FILE_VALIDATION: 1
        run: |
          cd tests
          coverage run --source=solnet -m unittest discover
          coverage xml
      - name: "Upload Coverage"
        if: ${{ matrix.python-version == '3.8' }}
        uses: codecov/codecov-action@v4
        with:
          directory: ./tests/
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true 
